language: csharp

mono:
  - latest

solution: mono-debug.sln

git:
  submodules: true

before_install:
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install 14
  - nvm use 14

install:
  - nuget restore mono-debug.sln
  - nuget restore external/debugger-libs/debugger-libs.sln
  - npm install

script:
  - npm test
